### Creates a new patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Rakim Mayers",
  "email": "rakim@flacko.com",
  "address": "Harlem, New York, NY",
  "dateOfBirth": "1988-10-03",
  "registeredDate": "2024-11-28"
}

###