### Creates a new patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Sergio Giavanni Kitchens",
  "email": "gunna@ysl.com",
  "address": "College Park, Atlanta, GA",
  "dateOfBirth": "1993-06-14",
  "registeredDate": "2024-11-28"
}

###