### Creates a new patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Jermaine Lamarr Cole",
  "email": "jcole@dreamville.com",
  "address": "2014 Forest Hills Dr, Fayetteville, NC",
  "dateOfBirth": "1985-01-28",
  "registeredDate": "2024-11-28"
}

###